name: CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-primary-key: never

      - uses: DeterminateSystems/flake-checker-action@v8

      - name: build
        uses: joerdav/run-xc@1.0.0
        with:
          task: build

      - name: docker-build
        uses: joerdav/run-xc@1.0.0
        with:
          task: docker-build-local-amd64

      - name: test
        uses: joerdav/run-xc@1.0.0
        with:
          task: test
