name: CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
      packages: "write"
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v12

      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - uses: DeterminateSystems/flake-checker-action@v8

      - name: Build flakegap
        run: nix build .#default

      - name: Build runtime
        run: nix build .#runtime
