name: CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v12

      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - uses: DeterminateSystems/flake-checker-action@v8

      - name: build
        uses: joerdav/run-xc@1.0.0
        with:
          task: build

      - name: docker-build
        uses: joerdav/run-xc@1.0.0
        with:
          task: docker-build

      - name: test
        uses: joerdav/run-xc@1.0.0
        with:
          task: test
