name: CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: Setup Docker GPG
        run: |
          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

          # Add the repository to Apt sources:
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update

      - name: Install Docker
        run: |
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v12

      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - uses: DeterminateSystems/flake-checker-action@v8

      - name: build
        uses: joerdav/run-xc@1.0.0
        with:
          task: build

      - name: docker-build
        uses: joerdav/run-xc@1.0.0
        with:
          task: docker-build

      - name: test
        uses: joerdav/run-xc@1.0.0
        with:
          task: test
