name: Build and push flakegap binary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      id-token: "write"
      contents: "read"
      packages: "write"
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v12

      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - uses: DeterminateSystems/flake-checker-action@v8

      - name: Run `nix build`
        run: nix build .

      - name: Create release
        run: gh release create ${{ github.ref_name }} --generate-notes

      - name: Upload
        run: gh release upload ${{ github.ref_name }} result/bin/flakegap --clobber
